# Generated by Django 4.2.3 on 2023-08-16 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soldier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=100)),
                ('lastNames', models.CharField(max_length=100)),
                ('rh', models.CharField(blank=True, max_length=3)),
                ('age', models.SmallIntegerField()),
                ('phoneNumber', models.CharField(max_length=20, unique=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Measures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('shoulders', models.FloatField(blank=True, null=True)),
                ('abds', models.FloatField(blank=True, null=True)),
                ('pectoral', models.FloatField(blank=True, null=True)),
                ('leftBicep', models.FloatField(blank=True, null=True)),
                ('rightBicep', models.FloatField(blank=True, null=True)),
                ('leftForearm', models.FloatField(blank=True, null=True)),
                ('rightForearm', models.FloatField(blank=True, null=True)),
                ('leftLeg', models.FloatField(blank=True, null=True)),
                ('RightLeg', models.FloatField(blank=True, null=True)),
                ('neck', models.FloatField(blank=True, null=True)),
                ('ass', models.FloatField(blank=True, null=True)),
                ('soldier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soldiers.soldier')),
            ],
        ),
        migrations.CreateModel(
            name='Assistence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registerDate', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(verbose_name='Activo:')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('soldier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soldiers.soldier')),
            ],
        ),
    ]
