# Generated by Django 4.2.3 on 2023-11-28 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soldiers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='soldier',
            table='Soldado',
        ),
    ]
