# Generated by Django 4.2.3 on 2023-11-29 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soldiers', '0002_alter_soldier_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soldier',
            options={'verbose_name': 'Soldado'},
        ),
    ]
