# Generated by Django 4.2.3 on 2023-11-29 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soldiers', '0003_alter_soldier_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assistence',
            options={'verbose_name': 'Asistencias'},
        ),
        migrations.AlterModelOptions(
            name='measures',
            options={'verbose_name': 'Medidas'},
        ),
        migrations.AlterModelTable(
            name='soldier',
            table=None,
        ),
    ]
