# Generated by Django 4.2.3 on 2023-11-29 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soldiers', '0004_alter_assistence_options_alter_measures_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assistence',
            options={'verbose_name': 'Asistencia'},
        ),
        migrations.AlterModelOptions(
            name='measures',
            options={'verbose_name': 'Medida'},
        ),
    ]
