# Generated by Django 4.2.3 on 2023-11-29 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soldiers', '0005_alter_assistence_options_alter_measures_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assistence',
            options={'verbose_name': 'Asistencia', 'verbose_name_plural': 'Asistencias'},
        ),
        migrations.AlterModelOptions(
            name='measures',
            options={'verbose_name': 'Medida', 'verbose_name_plural': 'Medidas'},
        ),
        migrations.AlterModelOptions(
            name='soldier',
            options={'verbose_name': 'Soldado', 'verbose_name_plural': 'Soldados'},
        ),
    ]
