# Generated by Django 4.2.3 on 2023-12-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldiers', '0006_alter_assistence_options_alter_measures_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldier',
            name='age',
            field=models.SmallIntegerField(verbose_name='Edad:'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='lastNames',
            field=models.CharField(max_length=100, verbose_name='Apellidos:'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='names',
            field=models.CharField(max_length=100, verbose_name='Nombres:'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Observaciones:'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='phoneNumber',
            field=models.CharField(max_length=20, unique=True, verbose_name='No. celular:'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='rh',
            field=models.CharField(blank=True, max_length=3, verbose_name='RH:'),
        ),
    ]
