# Generated by Django 4.2.3 on 2023-12-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldiers', '0007_alter_soldier_age_alter_soldier_lastnames_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldier',
            name='userPhoto',
            field=models.ImageField(blank=True, upload_to='uploads/', verbose_name='Foto:'),
        ),
    ]
