# Generated by Django 4.2.3 on 2023-12-11 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_options_alter_orderdetail_options'),
        ('soldiers', '0008_soldier_userphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistence',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Factura:'),
        ),
        migrations.AlterField(
            model_name='assistence',
            name='soldier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soldiers.soldier', verbose_name='Soldado:'),
        ),
        migrations.AlterField(
            model_name='assistence',
            name='status',
            field=models.BooleanField(verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='measures',
            name='RightLeg',
            field=models.FloatField(blank=True, null=True, verbose_name='Pierna derecha:'),
        ),
        migrations.AlterField(
            model_name='measures',
            name='abds',
            field=models.FloatField(blank=True, null=True, verbose_name='Abdomen:'),
        ),
        migrations.AlterField(
            model_name='measures',
            name='ass',
            field=models.FloatField(blank=True, null=True, verbose_name='Gluteo:'),
        ),
        migrations.AlterField(
            model_name='measures',
            name='height',
            field=models.FloatField(blank=True, null=True, verbose_name='Altura:'),
        ),
        migrations.AlterField(
            model_name='measures',
            name='leftBicep',
            field=models.FloatField(blank=True, null=True, verbose_name='Bicep izquierdo:'),
        ),
        migrations.AlterField(
            model_name='measures',
            name='leftForearm',
            field=models.FloatField(blank=True, null=True, verbose_name='Antebrazo izquierdo:'),
        ),
        migrations.AlterField(
            model_name='measures',
            name='leftLeg',
            field=models.FloatField(blank=True, null=True, verbose_name='Pierna izquierda:'),
        ),
        migrations.AlterField(
            model_name='measures',
            name='neck',
            field=models.FloatField(blank=True, null=True, verbose_name='Cuello:'),
        ),
        migrations.AlterField(
            model_name='measures',
            name='pectoral',
            field=models.FloatField(blank=True, null=True, verbose_name='Pectorales:'),
        ),
        migrations.AlterField(
            model_name='measures',
            name='rightBicep',
            field=models.FloatField(blank=True, null=True, verbose_name='Bicep derecho:'),
        ),
        migrations.AlterField(
            model_name='measures',
            name='rightForearm',
            field=models.FloatField(blank=True, null=True, verbose_name='Antebrazo derecho:'),
        ),
        migrations.AlterField(
            model_name='measures',
            name='shoulders',
            field=models.FloatField(blank=True, null=True, verbose_name='Hombros:'),
        ),
        migrations.AlterField(
            model_name='measures',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Peso:'),
        ),
    ]
