# Generated by Django 4.2.3 on 2023-12-12 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldiers', '0009_alter_assistence_order_alter_assistence_soldier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldier',
            name='userPhoto',
            field=models.ImageField(blank=True, upload_to='photos/', verbose_name='Foto:'),
        ),
    ]
