# Generated by Django 4.2.3 on 2023-12-15 20:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('soldiers', '0010_alter_soldier_userphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistence',
            name='registerDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
