# Generated by Django 4.2.3 on 2024-03-01 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldiers', '0012_alter_assistence_registerdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldier',
            name='email',
            field=models.EmailField(default='some@else.com', max_length=254, unique=True, verbose_name='Email:'),
        ),
    ]
