# Generated by Django 4.2.3 on 2024-03-07 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modificationDate', models.DateTimeField(auto_now=True)),
                ('methodPayment', models.CharField(max_length=50, verbose_name='Método de pago:')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Cantidad:')),
                ('startSuscription', models.DateTimeField(blank=True, null=True, verbose_name='Inicio de suscripción:')),
                ('endSuscription', models.DateTimeField(blank=True, null=True, verbose_name='Fin de suscripción:')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productserv', verbose_name='Producto:')),
            ],
            options={
                'verbose_name': 'Detalles de la Factura',
                'verbose_name_plural': 'Detalles de las Facturas',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='orderProducts',
            field=models.ManyToManyField(through='orders.OrderDetail', to='products.productserv'),
        ),
    ]
