# Generated by Django 4.2.3 on 2023-12-11 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productserv_category_alter_productserv_descrip_and_more'),
        ('soldiers', '0009_alter_assistence_order_alter_assistence_soldier_and_more'),
        ('orders', '0004_alter_order_options_alter_orderdetail_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='methodPayment',
            field=models.CharField(max_length=50, verbose_name='Método de pago:'),
        ),
        migrations.AlterField(
            model_name='order',
            name='soldier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soldiers.soldier', verbose_name='Soldado:'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='endSuscription',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fin de suscripción:'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productserv', verbose_name='Producto:'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Cantidad:'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='startSuscription',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inicio de suscripción:'),
        ),
    ]
