# Generated by Django 4.2.3 on 2023-12-11 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_methodpayment_alter_order_soldier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='endSuscription',
            field=models.DateField(blank=True, null=True, verbose_name='Fin de suscripción:'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='startSuscription',
            field=models.DateField(blank=True, null=True, verbose_name='Inicio de suscripción:'),
        ),
    ]
