# Generated by Django 4.2.3 on 2023-12-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_orderdetail_endsuscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='endSuscription',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fin de suscripción:'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='startSuscription',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inicio de suscripción:'),
        ),
    ]
