# Generated by Django 4.2.3 on 2023-08-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductServ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('descrip', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('PROD', 'Producto'), ('SERV', 'Servicio'), ('SUBS', 'Suscripcion ')], default='SUBS', max_length=4)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modificationDate', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(verbose_name='Activo')),
                ('price', models.IntegerField()),
            ],
        ),
    ]
