# Generated by Django 4.2.3 on 2023-12-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productserv_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productserv',
            name='category',
            field=models.CharField(choices=[('PROD', 'Producto'), ('SERV', 'Servicio'), ('SUBS', 'Suscripción ')], default='SUBS', max_length=4),
        ),
    ]
