# Generated by Django 4.2.3 on 2023-12-28 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productserv_price_currency_alter_productserv_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productserv',
            name='status',
        ),
        migrations.AlterField(
            model_name='productserv',
            name='category',
            field=models.CharField(choices=[('PROD', 'Producto'), ('SERV', 'Servicio'), ('SUBS', 'Suscripción')], default='SUBS', max_length=4, verbose_name='Categoría:'),
        ),
    ]
